### ISSUE TITLE
rspec test goes to page not found

### ISSUE THREAD

**Issue by wedesignstudios** [learn-co-curriculum/oo-student-scraper#41]
While working on the Scraper project I noticed the rspec test for `#scrape_index_page` uses an `index_url` variable set to http://127.0.0.1:4000/fixtures/student-site/index.html, which results in a page not found (./spec/scraper_spec.rb:26). The index page can, however, be brought up by using http://127.0.0.1:4000/. 

Is this an error within the rspec test? Should the `index_url` variable be set to http://127.0.0.1:4000/? When changed, the test passes for scrape_index_page class method.

Similar issue for the `#scrape_profile_page` test.

**Comment by mottigottlieb** [comment]
Are you running jekyll serve?

**Comment by wedesignstudios** [comment]
Yes, running jekyll serve.

**Comment by steveafrost** [comment]
See my comment on the other issue raised.

If jekyll serve is run from the jekyll directory, fixtures/student_site, then the index_url variable in the tests will not operate correctly. The jekyll serve command has to be run from the root directory. This is confusing because the lesson has a code snippet in it that says "you should be seeing this if run correctly" and shows jekyll serve run from the fixtures/student_site directory.

**Comment by aturkewi** [comment]
Just updated the spec so that it grabs the local html folder. No need to run a server and hit a URL.

Please keep raising issues if you see anything else, and thanks for helping us make Learn better!
