### ISSUE TITLE
Readme should state that the server must be run from `fixtures/student_site`

### ISSUE THREAD

**Issue by tibsar** [learn-co-curriculum/oo-student-scraper#43]
The readme does not make it clear that the server should be run from `fixtures/student_site`

**Comment by steveafrost** [comment]
I find the opposite is true. If jekyll serve is run from the jekyll directory, fixtures/student_site, then the index_url variable in the tests will not operate correctly. The jekyll serve command has to be run from the root directory. This is confusing because the lesson has a code snippet in it that says "you should be seeing this if run correctly" and shows jekyll serve run from the fixtures/student_site directory.

**Comment by aturkewi** [comment]
I just updated the spec so it just grabs the html file rather than running a server and hitting a url. We should be all set now :)
