### ISSUE TITLE
KNOWN ISSUES: HTTP Server errors

### ISSUE THREAD

**Issue by drakeltheryuujin** [learn-co-curriculum/oo-student-scraper#68]
Local and in-browser seem to work differently with the local directories. Tests may not pass unless local. Review PR #65.

**Comment by maxwellbenton** [comment]
Solution: Moved the included HTML student site to a new learn-co-curriculum repository here: https://github.com/learn-co-curriculum/student-scraper-test-page

Launched that repo as a github.io page so that students can visit the live site and scrape from it regardless of platform. Confirmed to be working both in a local environment and on the in-browser IDE.
